In [1]:
import pandas as pd
df = pd.read_csv('../data/dating_app_behavior.csv')
df.head(3)

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,...,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome,age,height_cm,weight_kg,zodiac_sign,body_type,relationship_intent
0,Prefer Not to Say,Gay,Urban,High,Bachelor’s,"Fitness, Politics, Traveling",52,Moderate,0.60,Optimistic,...,0.36,13,Early Morning,Mutual Match,56,149,40.6,Taurus,Curvy,Friends Only
1,Male,Bisexual,Suburban,Upper-Middle,No Formal Education,"Languages, Fashion, Parenting",279,Extreme User,0.56,Optimistic,...,0.42,0,Morning,Chat Ignored,40,155,69.7,Leo,Plus Size,Hookups
2,Non-binary,Pansexual,Suburban,Low,Master’s,"Movies, Reading, DIY",49,Moderate,0.41,Optimistic,...,0.41,1,After Midnight,Date Happened,30,185,96.9,Sagittarius,Curvy,Serious Relationship

In [2]:
df.isnull().sum()

gender                  0
sexual_orientation      0
location_type           0
income_bracket          0
education_level         0
interest_tags           0
app_usage_time_min      0
app_usage_time_label    0
swipe_right_ratio       0
swipe_right_label       0
likes_received          0
mutual_matches          0
profile_pics_count      0
bio_length              0
message_sent_count      0
emoji_usage_rate        0
last_active_hour        0
swipe_time_of_day       0
match_outcome           0
age                     0
height_cm               0
weight_kg               0
zodiac_sign             0
body_type               0
relationship_intent     0
dtype: int64

In [3]:
df.describe()

,app_usage_time_min,swipe_right_ratio,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,age,height_cm,weight_kg
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,149.912400,0.500655,99.526040,13.870280,2.98772,250.174400,50.07194,0.286205,11.521800,38.477920,172.584260,72.099052
std,86.990521,0.197468,57.996799,9.105615,1.99678,144.800996,29.16800,0.160042,6.920474,12.128435,16.134926,17.071441
min,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,18.000000,145.000000,37.800000
25%,74.000000,0.370000,49.000000,6.000000,1.00000,125.000000,25.00000,0.160000,5.000000,28.000000,159.000000,59.200000
50%,150.000000,0.500000,100.000000,13.000000,3.00000,250.000000,50.00000,0.270000,12.000000,38.000000,173.000000,70.300000
75%,225.000000,0.640000,150.000000,22.000000,5.00000,376.000000,75.00000,0.390000,18.000000,49.000000,187.000000,83.800000
max,300.000000,1.000000,200.000000,30.000000,6.00000,500.000000,100.00000,0.940000,23.000000,59.000000,200.000000,120.000000

In [4]:
df.columns

Index(['gender', 'sexual_orientation', 'location_type', 'income_bracket',
       'education_level', 'interest_tags', 'app_usage_time_min',
       'app_usage_time_label', 'swipe_right_ratio', 'swipe_right_label',
       'likes_received', 'mutual_matches', 'profile_pics_count', 'bio_length',
       'message_sent_count', 'emoji_usage_rate', 'last_active_hour',
       'swipe_time_of_day', 'match_outcome', 'age', 'height_cm', 'weight_kg',
       'zodiac_sign', 'body_type', 'relationship_intent'],
      dtype='object')

In [ ]:
categorical_features= ['gender', 'sexual_orientation', 'location_type', 'income_bracket', 'education_level', 
                       'interest_tags', 'app_usage_time_label', 'swipe_right_label', 'swipe_time_of_day', 'match_outcome', 'relationship_intent']

for feature in categorical_features:
    print(f"Unique {feature}: {df[feature].unique()}")
    print(f"Number of unique values{feature}: {df[feature].nunique()}\n")

Unique gender: ['Prefer Not to Say' 'Male' 'Non-binary' 'Genderfluid' 'Female'
 'Transgender']
Number of unique valuesgender: 6

Unique sexual_orientation: ['Gay' 'Bisexual' 'Pansexual' 'Lesbian' 'Asexual' 'Queer' 'Straight'
 'Demisexual']
Number of unique valuessexual_orientation: 8

Unique location_type: ['Urban' 'Suburban' 'Metro' 'Small Town' 'Remote Area' 'Rural']
Number of unique valueslocation_type: 6

Unique income_bracket: ['High' 'Upper-Middle' 'Low' 'Very Low' 'Middle' 'Lower-Middle'
 'Very High']
Number of unique valuesincome_bracket: 7

Unique education_level: ['Bachelor’s' 'No Formal Education' 'Master’s' 'Postdoc' 'Associate’s'
 'High School' 'Diploma' 'PhD' 'MBA']
Number of unique valueseducation_level: 9

Unique interest_tags: ['Fitness, Politics, Traveling' 'Languages, Fashion, Parenting'
 'Movies, Reading, DIY' ... 'Traveling, Fitness, Stand-up Comedy'
 'Gaming, Motorcycling, Art' 'Skating, Astrology, Hiking']
Number of unique valuesinterest_tags: 40206

Unique app_usage_time_label: ['Moderate' 'Extreme User' 'High' 'Addicted' 'Barely' 'Very Low' 'Low']
Number of unique valuesapp_usage_time_label: 7

Unique swipe_right_label: ['Optimistic' 'Balanced' 'Swipe Maniac' 'Choosy']
Number of unique valuesswipe_right_label: 4

Unique swipe_time_of_day: ['Early Morning' 'Morning' 'After Midnight' 'Evening' 'Late Night'
 'Afternoon']
Number of unique valuesswipe_time_of_day: 6

Unique match_outcome: ['Mutual Match' 'Chat Ignored' 'Date Happened' 'No Action'
 'One-sided Like' 'Blocked' 'Relationship Formed' 'Catfished' 'Ghosted'
 'Instant Match']
Number of unique valuesmatch_outcome: 10

Unique body_type: ['Curvy' 'Plus Size' 'Slim' 'Muscular' 'Athletic' 'Average']
Number of unique valuesbody_type: 6

Unique relationship_intent: ['Friends Only' 'Hookups' 'Serious Relationship' 'Exploring'
 'Casual Dating' 'Networking']
Number of unique valuesrelationship_intent: 6